clausi_wowroster_controller:
    path: /wowroster/index
    defaults: { _controller: clausi.wowroster.main.controller:index }

clausi_wowroster_controller_cron:
    path: /wowroster/cron/{key}
    defaults: { _controller: clausi.wowroster.main.controller:cron, key: ''}
